
install-java run:
	chmod u+x run
	sudo apt-get update

	// dash allows the next line to fail without stopping the build, e.g. if Python is already installed

	-sudo apt-get install default-jre
	-sudo apt-get install default-jdk
	echo $$PATH
	javac -cp json-simple-1.1.1.jar runner.java