install-python run:
	chmod u+x run
	sudo apt-get update
	# dash allows the next line to fail without stopping the build, e.g. if Python is already installed
	pip install PyContracts
	pwd
	cd ../../../my_python/
	pwd
	pip install -e .
	-sudo apt-get install -y python3
