#!/bin/bash

# This is the file "run": it runs the actual submission

python3 my_setup.py
python3 test_driver.py

# Downloading python package command that didn't work
# pwd
# cd ../../../my_python/
# pwd
# pip install -e .
